[project]
name = "TestOpenAI"
version = "0.1.0"
description = "Projekt TestOpenAI"
authors = [ { name = "Arkadiusz Burdon" } ]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
